title: "karen schoellkopf artwork"
description: "karen schoellkopf artwork"
url: "https://kgunette.github.io"
baseurl: ""

markdown: kramdown

collections:
  projects:
    output: true
    permalink: /projects/:name/

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"